version: '3'
services:
  alarms:
    build: './Alarms'
    ports:
      - "3000:3000"

  commands:
    build: './Command'
    ports:
      - "3001:3000"
  
  videos:
    build: './Videos'
    ports:
      - "3002:3000"
    volumes:
      - ./videos:/videos

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    depends_on:
      - alarms
      - commands
      - videos
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  