version: '3'
services:
  alarms:
    build: './alarms'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI= mongodb://db/microservices

  commands:
    build: './commands'
    ports:
      - "3001:3000"
  
  videos:
    build: './videos'
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI= mongodb://db/microservices
    volumes:
      - ./videos:/videos
    
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - alarms
      - commands
      - videos
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  